---

- name: Configure a graphical boot and shutdown animation using Plymouth
  collections: [ 'debops.debops' ]
  hosts: [ 'ypid_service_plymouth' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: grub
      grub_dependent_kernel_options: '{{ plymouth__grub__dependent_kernel_options }}'
      tags: [ 'role::grub' ]

    - role: ypid.plymouth
      tags: [ 'role::plymouth' ]
